name: Deployment pipeline

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Healthcheck
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fsopen-pokedex-makeri89.herokuapp.com
          max-attempts: 3
          retry-delay: 5s